replicas: 2

image:
  clickhouseServer: yandex/clickhouse-server:latest
  clickhouseClient: yandex/clickhouse-client:latest

service:
  name: clickhouse-service
  type: ClusterIP

ports:
  - name: http
    protocol: TCP
    port: 8123
    targetPort: 8123
  - name: native
    protocol: TCP
    port: 9000
    targetPort: 9000

configVolume:
  name: config-volume
  mountPath: /etc/clickhouse-server/config.d

configMap:
  name: clickhouse-config
  defaultMode: 0644

serviceAccount:
  create: true

ingress:
  enabled: false

autoscaling:
  enabled: false

